<?xml version="1.0"?>
<robot name="workcell" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find iiwa_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find iiwa_description)/urdf/iiwa7.xacro"/>

  <xacro:arg name="table_size" default="1.5"/>
  <xacro:arg name="hardware_interface" default="PositionJointInterface"/>
  <xacro:arg name="robot_name" default="iiwa"/>

  <xacro:property name="INCH_TO_METER" value="0.0254"/><!--meters/inches-->
  <xacro:property name="pointer_length" value="7.50"/><!--inches-->
  
  <xacro:property name="IIWA_MF_DIAMETER" value ="0.063"/>
  <xacro:property name="IIWA_MF_LENGTH" value ="0.061"/>
  
  <xacro:property name="TOOL_FACE_LENGTH" value="0.10668"/>
  <xacro:property name="TOOL_FACE_THICKNESS" value="0.00635"/>
  <xacro:property name="TOOL_FACE_MOUNT_LOC_Z" value="0.1016"/>

  <xacro:property name="BASE_PLATE_THICKNESS" value="0.00635"/>
  <xacro:property name="BASE_PLATE_LENGTH" value="0.762"/>
  <xacro:property name="BASE_PLATE_WIDTH" value="0.3048"/>
  
  <xacro:property name="CAMERA_WIDTH" value="0.02005"/>

  <!-- ====================== LINKS ========================= -->
  <link name="world"/>

  <!-- table -->
  <link name="table">
    <visual>
      <origin xyz="0 0 -0.05"/>
      <geometry>
        <box size="$(arg table_size) $(arg table_size) 0.1"/>
      </geometry>
      <material name="StainlessSteel">
        <color rgba="0.8 0.8 0.8 0.9"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.05"/>
      <geometry>
        <box size="$(arg table_size) $(arg table_size) 0.1"/>
      </geometry>
    </collision>
  </link>
  
  <link name="base_plate">
    <visual>
      <origin xyz="${0.5 * BASE_PLATE_WIDTH} ${0.5 * BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
      <geometry>
        <box size="${BASE_PLATE_WIDTH} ${BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
      </geometry>
      <material name="StainlessSteel">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${0.5 * BASE_PLATE_WIDTH} ${0.5 * BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
      <geometry>
        <box size="${BASE_PLATE_WIDTH} ${BASE_PLATE_LENGTH} ${BASE_PLATE_THICKNESS}"/>
      </geometry>
      <material name="StainlessSteel">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </collision>
  </link>

  <!-- teach box -->
  <link name="teach_box">
    <visual>
      <origin xyz="0 0 -0.17"/>
      <geometry>
       <mesh filename="package://vpr_support/meshes/teachbox.STL"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <!-- <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://vpr_support/meshes/teachbox.STL"/>
      </geometry>
    </collision> -->
  </link>
  
  <link name="iiwa_mounting_flange">
    <visual>
      <origin xyz="0 0 ${0.5*IIWA_MF_LENGTH}"/>
      <geometry>
       <cylinder radius="${0.5 * IIWA_MF_DIAMETER}" length="${IIWA_MF_LENGTH}"/>
      </geometry>
      <material name="light_gray">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${0.5*IIWA_MF_LENGTH}"/>
      <geometry>
       <cylinder radius="${0.5 * IIWA_MF_DIAMETER}" length="${IIWA_MF_LENGTH}"/>
      </geometry>
      <material name="light_gray">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </collision>
  </link>

  <link name="eef_toolface">
    <visual>
      <geometry>
        <mesh filename="package://vpr_support/meshes/TEACH_EEF.STL"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://vpr_support/meshes/TEACH_EEF.STL"/>
      </geometry>
    </collision>
  </link>  
  <link name="eef_toolface_mount_location"/>

  <link name="tcp"/>
  <link name="camera_base_link"/>

  <!-- ====================== JOINTS ========================= -->
  <joint name="world_to_table_joint" type="fixed">
    <origin xyz="0 0 1.0"/>
    <parent link="world"/>
    <child link="table"/>
  </joint>

  <joint name="table_to_teach_box" type="floating">
    <parent link="table"/>
    <child link="teach_box"/>
  </joint>
  
  <joint name="table_to_base_plate" type="fixed">
    <origin xyz="${-0.5*$(arg table_size) + 0.1397 } ${-0.5*$(arg table_size) + 0.09525} 0.0" rpy="0 0 0"/>
     <parent link="table"/>
     <child link="base_plate"/>
  </joint>
  
  <joint name="iiwa_to_mounting_flange" type="fixed">
    <origin xyz="0.0 0.0 0.0"/>
    <parent link="iiwa_link_7"/>
    <child link="iiwa_mounting_flange"/>
  </joint>
  
  <joint name="$(arg robot_name)_to_eef_toolface" type="fixed">
    <origin xyz="0.0 0.0 ${IIWA_MF_LENGTH}" rpy="0.0 0.0 ${0.5 * pi}"/>
    <parent link="iiwa_mounting_flange"/>
    <child link="eef_toolface"/>
  </joint>
  <joint name="$(arg robot_name)_to_eef_mount_location" type="fixed">
    <!-- <origin xyz="0.0 ${-TOOL_FACE_MOUNT_LOC_Z} ${TOOL_FACE_THICKNESS}" rpy="0.0 0.0 0.0"/> --> 
    <origin xyz="0.035 -0.08 -0.01" rpy="0.0 0.0 0.0"/>
    <parent link="eef_toolface"/>
    <child link="eef_toolface_mount_location"/>
  </joint>
  
  <joint name="$(arg robot_name)_to_camera_base" type="fixed">
    <origin xyz="0.0 0.0 ${0.5 * CAMERA_WIDTH}" rpy="0.0 0.0 0.0"/>
    <parent link="eef_toolface_mount_location"/>
    <child link="camera_base_link"/>
  </joint>

  <joint name="eef_toolface_to_tcp" type="fixed">
    <origin xyz="0.0 0.0 ${pointer_length * INCH_TO_METER}"/>
    <parent link="eef_toolface"/>
    <child link="tcp"/>
  </joint>

  <!--iiwa-->
  <xacro:iiwa7 hardware_interface="$(arg hardware_interface)"
               robot_name="$(arg robot_name)"
               parent="table">
    <origin xyz="-0.5 -0.5 ${BASE_PLATE_THICKNESS}" rpy="0 0 0"/>
  </xacro:iiwa7>

</robot>
